"""The menu subcommand: a Nilesoft Shell context menu."""

from __future__ import annotations

import os
import re
import shutil
import sys
from pathlib import Path

from .console import console

IMPORT_LINE = "import 'imports/shrencode.nss'"
IMPORT_PATTERN = re.compile(r"^[ \t]*import[ \t]+['\"]imports[/\\]shrencode\.nss['\"][ \t]*\r?$", re.I | re.M)

ICON = (
    '<svg fill="none" viewBox="0 0 16 16">'
    '<path fill="@image.color1" d="M13.06 4.35L9.65 0.94c-0.29 -0.28 -0.66 -0.44 -1.06 -0.44H4C3.17 0.5 2.5 1.17 2.5 2v12c0 0.83 0.67 1.5 1.5 1.5h8c0.83 0 1.5 -0.67 1.5 -1.5V5.41c0 -0.4 -0.16 -0.77 -0.44 -1.06ZM11.79 4.5h-1.79c-0.28 0 -0.5 -0.22 -0.5 -0.5v-1.79l2.29 2.29ZM12.5 14c0 0.28 -0.22 0.5 -0.5 0.5H4c-0.28 0 -0.5 -0.22 -0.5 -0.5V2c0 -0.28 0.22 -0.5 0.5 -0.5h4.5v2.5c0 0.83 0.67 1.5 1.5 1.5h2.5v8.5Z"/>'
    '<path fill="@image.color1" d="M11.045 11.72c-0.111 0 -0.222 -0.037 -0.312 -0.109l-2.155 -1.72c-0.119 -0.095 -0.188 -0.238 -0.188 -0.391s0.069 -0.296 0.188 -0.391l2.155 -1.72c0.149 -0.121 0.355 -0.143 0.528 -0.06 0.173 0.083 0.283 0.259 0.283 0.451v3.439c0 0.192 -0.11 0.367 -0.283 0.45 -0.069 0.033 -0.143 0.05 -0.217 0.05Z"/>'
    '<path fill="@image.color1" d="M4.955 11.72c-0.074 0 -0.148 -0.017 -0.217 -0.05 -0.173 -0.083 -0.283 -0.258 -0.283 -0.45v-3.439c0 -0.192 0.11 -0.367 0.283 -0.451 0.173 -0.084 0.379 -0.06 0.529 0.06l2.155 1.72c0.119 0.095 0.188 0.238 0.188 0.391s-0.069 0.296 -0.188 0.391l-2.155 1.72c-0.09 0.072 -0.201 0.109 -0.312 0.109Z"/>'
    "</svg>"
)

VIDEO_FILTER = ".mov|.mp4|.m4v|.mkv|.avi|.mxf|.mts|.m2ts|.ts|.webm|.wmv|.mpg|.mpeg|.vob|.flv|.dv|.3gp"

ENCODER_MENUS = {
    "x265": [
        ("High quality", "-e x265 --quality high"),
        ("Balanced", "-e x265 --quality balanced"),
        ("Compact", "-e x265 --quality compact"),
        ("Min VMAF 95", "-e x265 --min-vmaf 95"),
        ("Balanced MP4", "-e x265 --container mp4"),
    ],
    "SVT-AV1": [
        ("High quality", "-e svt-av1 --quality high"),
        ("Balanced", "-e svt-av1 --quality balanced"),
        ("Compact", "-e svt-av1 --quality compact"),
    ],
}


def launchers() -> tuple[tuple[str, str], tuple[str, str]]:
    """(program, argument prefix) for console runs and for windowless runs."""
    if getattr(sys, "frozen", False):
        exe = Path(sys.executable)
        gui = exe.with_name("shrencodew.exe")
        return (str(exe), ""), (str(gui if gui.is_file() else exe), "")
    cli, gui = shutil.which("shrencode"), shutil.which("shrencodew")
    if cli:
        return (cli, ""), (gui or cli, "")
    python = Path(sys.executable)
    pythonw = python.with_name("pythonw.exe")
    return (str(python), "-m shrencode "), (str(pythonw if pythonw.is_file() else python), "-m shrencode ")


def nss_string(text: str) -> str:
    """Single-quoted Nilesoft string: no escapes, @ starts an expression."""
    return "'" + text.replace("@", "@@") + "'"


def render(program: tuple[str, str], windowless: tuple[str, str]) -> str:
    def item(title: str, args: str, gui: bool = False, extra: str = "") -> str:
        exe, prefix = windowless if gui else program
        return (
            f"item(title={nss_string(title)}{extra} invoke=0 cmd={nss_string(exe)} "
            f"args='{prefix}{args} @sel(true)')"
        )

    def encoder_menus(indent: str, extra_args: str) -> list[str]:
        lines = []
        for title, entries in ENCODER_MENUS.items():
            lines.append(f"{indent}menu(title={nss_string(title)})")
            lines.append(f"{indent}{{")
            for label, args in entries:
                lines.append(f"{indent}\t" + item(label, f"encode {args}{extra_args} --pause"))
            lines.append(f"{indent}}}")
        return lines

    out = [
        "// Generated by shrencode menu install. Changes are overwritten on reinstall;",
        "// run shrencode menu uninstall to remove.",
        "",
        # image= needs an image value; a plain string is read as a file path. The @ in
        # @image.color1 stays unescaped so Nilesoft fills in the theme colour.
        f"$svg_shrencode = image.svg('{ICON}')",
        "",
        f"menu(type='file' mode='multiple' find='{VIDEO_FILTER}' title='shrencode' image=svg_shrencode)",
        "{",
        "\t" + item("Compare", "compare", gui=True, extra=" where=sel.count==2 sep=after"),
        "\t" + item("Encode", "encode --pause"),
        "\t" + item("Encode and compare", "encode --compare --pause"),
        "\tseparator",
        *encoder_menus("\t", ""),
        "\tseparator",
        "\t" + item("Analyze", "encode --dry-run -v --pause"),
        "}",
        "",
        "menu(type='dir' mode='multiple' title='shrencode' image=svg_shrencode)",
        "{",
        "\t" + item("Encode", "encode -r --pause"),
        "\tseparator",
        *encoder_menus("\t", " -r"),
        "\tseparator",
        "\t" + item("Analyze", "encode -r --dry-run -v --pause"),
        "}",
        "",
    ]
    return "\n".join(out)


def _registry_locations() -> list[Path]:
    if os.name != "nt":
        return []
    import winreg

    found = []
    roots = [
        (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall"),
        (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall"),
        (winreg.HKEY_CURRENT_USER, r"SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall"),
    ]
    for hive, path in roots:
        try:
            with winreg.OpenKey(hive, path) as key:
                for i in range(winreg.QueryInfoKey(key)[0]):
                    try:
                        with winreg.OpenKey(key, winreg.EnumKey(key, i)) as app:
                            name = winreg.QueryValueEx(app, "DisplayName")[0]
                            if "nilesoft" not in str(name).lower():
                                continue
                            for value in ("InstallLocation", "DisplayIcon"):
                                try:
                                    loc = str(winreg.QueryValueEx(app, value)[0]).strip('"').split(",")[0]
                                    p = Path(loc)
                                    found.append(p if p.is_dir() else p.parent)
                                except OSError:
                                    pass
                    except OSError:
                        continue
        except OSError:
            continue
    return found


def find_nilesoft(hint: str | None) -> Path | None:
    candidates: list[Path] = []
    if hint:
        candidates.append(Path(hint))
    for var in ("ProgramFiles", "ProgramW6432", "LOCALAPPDATA"):
        if os.environ.get(var):
            candidates.append(Path(os.environ[var]) / "Nilesoft Shell")
            candidates.append(Path(os.environ[var]) / "Programs" / "Nilesoft Shell")
    candidates.append(Path.home() / "scoop" / "apps" / "nilesoft-shell" / "current")
    candidates += _registry_locations()
    for c in candidates:
        if (c / "shell.nss").is_file():
            return c
    return None


def _read(path: Path) -> tuple[str, bool]:
    raw = path.read_bytes()
    bom = raw.startswith(b"\xef\xbb\xbf")
    return raw.decode("utf-8-sig", errors="replace"), bom


def _write(path: Path, text: str, bom: bool) -> None:
    path.write_bytes((b"\xef\xbb\xbf" if bom else b"") + text.encode("utf-8"))


def install(root: Path) -> None:
    (root / "imports").mkdir(exist_ok=True)
    target = root / "imports" / "shrencode.nss"
    target.write_text(render(*launchers()), encoding="utf-8")
    config, bom = _read(root / "shell.nss")
    if not IMPORT_PATTERN.search(config):
        eol = "\r\n" if "\r\n" in config else "\n"
        config = config.rstrip("\r\n") + eol + IMPORT_LINE + eol
        _write(root / "shell.nss", config, bom)
    console.result(f"installed {target}")


def uninstall(root: Path) -> None:
    target = root / "imports" / "shrencode.nss"
    config, bom = _read(root / "shell.nss")
    lines = config.splitlines(keepends=True)
    cleaned = "".join(line for line in lines if not IMPORT_PATTERN.match(line.rstrip("\r\n")))
    if cleaned != config:
        _write(root / "shell.nss", cleaned, bom)
    if target.exists():
        target.unlink()
    console.result(f"removed {target}")


def run_menu(args) -> int:
    if args.action == "show":
        print(render(*launchers()))
        return 0
    root = find_nilesoft(args.nilesoft)
    if not root:
        console.error("Nilesoft Shell not found; pass its folder with --nilesoft")
        return 1
    try:
        install(root) if args.action == "install" else uninstall(root)
    except PermissionError:
        console.error(f"no write access to {root}; run this from an administrator terminal")
        return 1
    console.info(console.dim("hold ctrl and right-click the desktop to reload Nilesoft Shell"))
    return 0
